# Generated by Django 6.0.3 on 2026-04-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeridentity',
            name='profile_avatar',
            field=models.TextField(blank=True),
        ),
    ]
