# Generated by Django 6.0.3 on 2026-04-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_playeridentity_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_credential', to='accounts.playeridentity')),
            ],
        ),
    ]
